Repository ArneBinder/pie-datasets, pull requests merged in 2023-11, with the labels that each got.

#11 fix coverage score (and report) for unused source files
  tests/conftest.py
Labels: bug

#16 fix importing all modules in conftest.py
  tests/conftest.py
Labels: bug

#14 add conll2003 dataset
  dataset_builders/pie/conll2003/README.md
  dataset_builders/pie/conll2003/conll2003.py
  tests/dataset_builders/pie/test_conll2003.py
Labels: new dataset

#17 add "Document Converters" section to conll2003 dataset card
  dataset_builders/pie/conll2003/README.md
Labels: bug

#19 implement `RegexPartitioner`
  src/pie_datasets/document/processing/__init__.py
  src/pie_datasets/document/processing/regex_partitioner.py
  tests/unit/document/processing/test_regex_partitioner.py
Labels: enhancement

#20 implement `TextSpanTrimmer`
  src/pie_datasets/document/processing/__init__.py
  src/pie_datasets/document/processing/text_span_trimmer.py
  tests/unit/document/processing/test_text_span_trimmer.py
Labels: enhancement

#23 add `codecov.yml` to set target coverage to 90%
  codecov.yml
Labels: ci, testing

#24 add codecov threshold
  codecov.yml
Labels: ci, testing

#25 codecov ci: set target to 90% for the patch job
  codecov.yml
Labels: ci, testing

#12 add generic `brat` dataset
  dataset_builders/pie/brat/README.md
  dataset_builders/pie/brat/brat.py
  tests/dataset_builders/common.py
  tests/dataset_builders/pie/test_brat.py
  tests/fixtures/dataset_builders/pie/brat/train/1.ann
  tests/fixtures/dataset_builders/pie/brat/train/1.txt
  tests/fixtures/dataset_builders/pie/brat/train/2.ann
  tests/fixtures/dataset_builders/pie/brat/train/2.txt
Labels: new dataset

#30 do not assert minimum test coverage via pytest
  .github/workflows/test.yaml
Labels: ci

#31 remove leftovers from datasets in pytorch-ie
  dataset_builders/pie/conll2003/conll2003.py
  src/pie_datasets/document/processing/regex_partitioner.py
Labels: bug

#45 add usage documentation from `pytorch-ie` README.md
  README.md
Labels: documentation

#46 improve documentation
  README.md
Labels: documentation

#54 Add AM dataset SciDTB_Argmin
  dataset_builders/pie/scidtb_argmin/README.md
  dataset_builders/pie/scidtb_argmin/requirements.txt
  dataset_builders/pie/scidtb_argmin/scidtb_argmin.py
  poetry.lock
  pyproject.toml
  tests/dataset_builders/pie/test_scidtb_argmin.py
  tests/fixtures/dataset_builders/hf/scidtb_argmin/train.0.json
  tests/fixtures/dataset_builders/scidtb_argmin_annotations.tgz
Labels: new dataset

#57 make `BratBuilder` re-usable
  dataset_builders/pie/brat/brat.py
  src/pie_datasets/builders/__init__.py
  src/pie_datasets/builders/brat.py
  src/pie_datasets/document/types.py
  tests/dataset_builders/pie/test_brat.py
Labels: enhancement

#58 `document_converters` as property of `PieDatasetBuilder`
  src/pie_datasets/core/builder.py
Labels: enhancement

#59 add generic document processors: `Caster`, `Converter`, `Pipeline`
  dataset_builders/pie/scidtb_argmin/scidtb_argmin.py
  dataset_builders/pie/tacred/tacred.py
  src/pie_datasets/document/processing/__init__.py
  src/pie_datasets/document/processing/generic.py
  src/pie_datasets/document/processing/tokenization.py
  src/pie_datasets/statistics/span_length_collector.py
  tests/dataset_builders/pie/test_cdcp.py
  tests/dataset_builders/pie/test_scidtb_argmin.py
  tests/unit/document/processing/test_generic.py
  tests/unit/document/processing/test_tokenization.py
Labels: enhancement, breaking

#60 add document processor: `RelationArgumentSorter`
  src/pie_datasets/document/processing/__init__.py
  src/pie_datasets/document/processing/relation_argument_sorter.py
  tests/unit/document/processing/test_relation_argument_sorter.py
Labels: enhancement

#62 fix `pie-datasets` version ranges in dataset loading scripts
  dataset_builders/pie/brat/requirements.txt
  dataset_builders/pie/cdcp/requirements.txt
  dataset_builders/pie/conll2003/requirements.txt
  dataset_builders/pie/scidtb_argmin/requirements.txt
  dataset_builders/pie/tacred/requirements.txt
Labels: bug

#70 import `pie-models` instead of `pytorch-ie`
  dataset_builders/pie/cdcp/cdcp.py
  dataset_builders/pie/scidtb_argmin/scidtb_argmin.py
  dataset_builders/pie/tacred/tacred.py
  poetry.lock
  pyproject.toml
  src/pie_datasets/document/processing/__init__.py
  src/pie_datasets/document/processing/regex_partitioner.py
  src/pie_datasets/document/processing/relation_argument_sorter.py
  src/pie_datasets/document/processing/text_span_trimmer.py
  src/pie_datasets/document/processing/tokenization.py
  src/pie_datasets/statistics/__init__.py
  src/pie_datasets/statistics/span_length_collector.py
  tests/dataset_builders/pie/test_cdcp.py
  tests/dataset_builders/pie/test_scidtb_argmin.py
  tests/unit/document/processing/test_regex_partitioner.py
  tests/unit/document/processing/test_relation_argument_sorter.py
  tests/unit/document/processing/test_text_span_trimmer.py
  tests/unit/document/processing/test_tokenization.py
  tests/unit/test_statistics.py
Labels: breaking

#75 fix `brat` dataset card and set base revision
  dataset_builders/pie/brat/README.md
  dataset_builders/pie/brat/brat.py
Labels: documentation

#77 make `pie-modules` a dev dependency
  dataset_builders/pie/cdcp/requirements.txt
  dataset_builders/pie/scidtb_argmin/requirements.txt
  dataset_builders/pie/tacred/requirements.txt
  poetry.lock
  pyproject.toml
Labels: breaking

#78 fix release workflow
  README.md
Labels: documentation

#80 fix release workflow again
  README.md
Labels: documentation
