Repository ArneBinder/pie-datasets, pull requests merged in 2024-07, with the labels that each got.

#134 Biorel dataset [WIP]
  dataset_builders/pie/biorel/README.md
  dataset_builders/pie/biorel/biorel.py
  dataset_builders/pie/biorel/requirements.txt
  tests/dataset_builders/pie/biorel/test_biorel.py
Labels: new dataset

#139 biorel: remove warning when entity name is not the same as the span text
  dataset_builders/pie/biorel/biorel.py
Labels: bug

#144 poetry dependencies for torch in macOS with M-series
  poetry.lock
  pyproject.toml
Labels: bug

#143 add brat note
  src/pie_datasets/builders/brat.py
  tests/unit/builder/test_brat_builder.py
Labels: enhancement
