Repository ArneBinder/pie-datasets, pull requests merged in 2024-04, with the labels that each got.

#106 add DrugProt dataset
  .gitignore
  dataset_builders/pie/drugprot/README.md
  dataset_builders/pie/drugprot/drugprot.py
  dataset_builders/pie/drugprot/requirements.txt
  poetry.lock
  pyproject.toml
  tests/dataset_builders/pie/test_drugprot.py
Labels: new dataset

#116 fix `DatasetDict.select` with document converters
  src/pie_datasets/core/dataset_dict.py
Labels: bug

#118 fix CI for dataset tests
  .github/workflows/test.yaml
  .github/workflows/test_datasets.yaml
Labels: bug, ci

#123 brat: use annotation types from pytorch-ie
  poetry.lock
  pyproject.toml
  src/pie_datasets/builders/brat.py
  tests/unit/builder/test_brat_builder.py
Labels: breaking

#125 fix datset test CI when no dataset was modified
  .github/workflows/test_pie_datasets.yaml
Labels: ci

#52 add `conll2012_ontonotesv5` dataset
  dataset_builders/pie/conll2012_ontonotesv5/README.md
  dataset_builders/pie/conll2012_ontonotesv5/conll2012_ontonotesv5.py
  dataset_builders/pie/conll2012_ontonotesv5/requirements.txt
  tests/dataset_builders/pie/conll2012_ontonotesv5/test_conll2012_ontonotesv5.py
  tests/fixtures/dataset_builders/hf/conll2012_ontonotesv5/example.json
Labels: new dataset

#126 increase timeout for test_dataset CI job
  .github/workflows/test_pie_datasets.yaml
Labels: ci

#127 fix `aae2` when passing `conversion_method` to `load_dataset`
  dataset_builders/pie/aae2/aae2.py
Labels: bug
